version: '3.9'

services:
  samba:
    image: daniele/samba:4.13.3_4
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - configs:/configs
      - music:/music
      - movies:/movies
      - pictures:/pictures
      - books:/books
      - homevideos:/homevideos
      - daniele:/daniele
      - radhika:/radhika
      - arya:/arya
      - rishi:/rishi
    command: >
      -i "/configs/users.smbpasswd"
      -s "radhika;/radhika;yes;no;no;radhika,daniele"  
      -s "daniele;/daniele;yes;no;no;daniele"
      -s "arya;/arya;yes;no;no;arya,radhika,daniele"  
      -s "rishi;/rishi;yes;no;no;rishi,radhika,daniele"
      -s "music;/music;yes;yes;yes;daniele,radhika,arya,rishi;;daniele"
      -s "movies;/movies;yes;yes;yes;daniele,radhika,arya,rishi;;daniele"
      -s "pictures;/pictures;yes;yes;no;daniele,radhika,arya,rishi;;daniele"
      -s "books;/books;yes;yes;yes;daniele,radhika,arya,rishi;;daniele"
      -s "homevideos;/homevideos;yes;yes;no;daniele,radhika,arya,rishi;;daniele"
      -S
        
  avahi:
    image: stanback/alpine-avahi
    network_mode: "host"
    restart: always
    volumes:
      - ${PWD}/services:/etc/avahi/services
       

networks:
  default:

volumes:
  configs:
    driver: local-persist
    driver_opts:
      mountpoint: /home/daniele/smbconfigs
  music:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/music
  movies:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/movies
  books:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/books
  homevideos:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/homevideos
  pictures:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/pictures
  daniele:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/documents/daniele
  radhika:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/documents/rdutt
  arya:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/documents/arya
  rishi:
    driver: local-persist
    driver_opts:
      mountpoint: /vastocean/documents/rishi
    
